// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int big = 0;
		int small = 0;
		while (N>0){
			if (Math.random() > 0.5)
				big ++;
			else
				small ++;
			N--;
		}
		if (small == 0){
			System.out.println("> 0.5:  " + big + " times");
			System.out.println("<= 0.5: " + small + " times");
		}
		else{
		System.out.println("> 0.5:  " + big + " times");
		System.out.println("<= 0.5: " + small + " times");
		System.out.println("Ratio:  " + (float) big / (float) small);
		}
	}
}
